name: Examples Checks
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - examples/**

env:
  AWS_DEFAULT_REGION: us-west-2
  TF_PLUGIN_CACHE_DIR: $HOME/.terraform.d/plugin-cache

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-terraform-plugin-cache
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - name: terraform
      run: |
        for DIR in $(find ./examples ! -path ./examples -type d); do
          pushd $DIR
          if [ -f terraform.template.tfvars ]; then
            cp terraform.template.tfvars terraform.tfvars
          fi
          echo; echo -e "\e[1;35m===> Initializing Example: $DIR <===\e[0m"; echo
          TF_LOG=TRACE terraform init
          echo; echo -e "\e[1;35m===> Format Checking Example: $DIR <===\e[0m"; echo
          terraform fmt -check
          echo; echo -e "\e[1;35m===> Validating Example: $DIR <===\e[0m"; echo
          terraform validate
          popd
        done
