name: Examples Checks
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - examples/**

env:
  AWS_DEFAULT_REGION: us-west-2
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["0.11.14", "0.12.24"]
    steps:
    - uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-terraform-plugin-cache
        path: ${{ env.TF_PLUGIN_CACHE_DIR }}
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ matrix.terraform_version }}
    - name: terraform
      run: |
        for DIR in $(find ./examples -type f -name '*.tf' -exec dirname {} \; | sort -u); do
          if [ ${{ matrix.terraform_version }} = 0.11.14 ]; then
            # Skip examples already converted to Terraform 0.12 only syntax
            if [ $DIR = ./examples/eks-getting-started ]; then
              continue
            fi
          fi
          pushd $DIR
          if [ -f terraform.template.tfvars ]; then
            cp terraform.template.tfvars terraform.tfvars
          fi
          echo; echo -e "\e[1;35m===> Initializing Example: $DIR <===\e[0m"; echo
          terraform init
          if [ ${{ matrix.terraform_version }} != 0.11.14 ]; then
            echo; echo -e "\e[1;35m===> Format Checking Example: $DIR <===\e[0m"; echo
            terraform fmt -check
          fi
          echo; echo -e "\e[1;35m===> Validating Example: $DIR <===\e[0m"; echo
          terraform validate
          popd
        done
