name: Infrastructure Repository Checks
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - infrastructure/repository/**

defaults:
  run:
    working-directory: infrastructure/repository

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "0.12.24"
    - run: terraform init
    - run: terraform fmt -check
    - run: terraform validate
