name: Terraform Provider Checks
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - aws/**
      - docs/index.md
      - docs/data-sources/**
      - docs/guides/**
      - docs/resources/**
      - main.go
      - website/**

env:
  AWS_DEFAULT_REGION: us-west-2
  GO_VERSION: "1.14"
  TERRAFORM_VERSION: "0.12.24"

jobs:
  go_build:
    name: go build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/cache@v1
      id: cache-terraform-plugin-dir
      with:
        path: terraform-plugin-dir
        key: ${{ runner.os }}-terraform-plugin-dir-${{ hashFiles('**/go.sum') }}-${{ hashFiles('aws/**') }}
    - uses: actions/cache@v1
      if: steps.cache-terraform-plugin-dir.outputs.cache-hit != 'true'
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('**/go.sum') }}
    - run: go mod download
    - name: go build
      if: steps.cache-terraform-plugin-dir.outputs.cache-hit != 'true'
      run: go build -o terraform-plugin-dir/terraform-provider-aws_v99.99.99_x4 .
  terraform_providers_schema:
    name: terraform providers schema
    needs: [go_build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: terraform-plugin-dir
        key: ${{ runner.os }}-terraform-plugin-dir-${{ hashFiles('**/go.sum') }}-${{ hashFiles('aws/**') }}
    - uses: actions/cache@v1
      id: cache-terraform-providers-schema
      with:
        path: terraform-providers-schema
        key: ${{ runner.os }}-terraform-providers-schema-${{ hashFiles('**/go.sum') }}-${{ hashFiles('aws/**') }}
    - uses: hashicorp/setup-terraform@v1
      if: steps.cache-terraform-providers-schema.outputs.cache-hit != 'true'
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false
    - name: terraform init
      if: steps.cache-terraform-providers-schema.outputs.cache-hit != 'true'
      run: |
        # We need a file to initialize the provider
        echo 'data "aws_partition" "example" {}' > example.tf
        terraform init -plugin-dir terraform-plugin-dir
    - name: terraform providers schema
      if: steps.cache-terraform-providers-schema.outputs.cache-hit != 'true'
      run: |
        mkdir terraform-providers-schema
        terraform providers schema -json > terraform-providers-schema/schema.json
  tfproviderdocs:
    needs: [terraform_providers_schema]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('**/go.sum') }}
    - uses: actions/cache@v1
      with:
        path: terraform-providers-schema
        key: ${{ runner.os }}-terraform-providers-schema-${{ hashFiles('**/go.sum') }}-${{ hashFiles('aws/**') }}
    - run: go install github.com/bflad/tfproviderdocs
    - name: tfproviderdocs check
      run: |
        tfproviderdocs check \
          -allowed-resource-subcategories-file website/allowed-subcategories.txt \
          -ignore-side-navigation-data-sources aws_alb,aws_alb_listener,aws_alb_target_group,aws_kms_secret \
          -provider-name aws \
          -providers-schema-json schema.json \
          -require-resource-subcategory
