name: Terraform Provider Checks
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - aws/**
      - docs/index.md
      - docs/data-sources/**
      - docs/guides/**
      - docs/resources/**
      - main.go
      - website/**

env:
  AWS_DEFAULT_REGION: us-west-2
  GO_VERSION: "1.14"
  TERRAFORM_VERSION: "0.12.24"

jobs:
  go_build:
    name: go build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: go env
      run: |
        echo "::set-env name=GOBIN::$(go env GOBIN)"
        echo "::set-env name=GOCACHE::$(go env GOCACHE)"
    - uses: actions/cache@v1
      with:
        path: ${{ env.GOBIN }}
        key: ${{ runner.os }}-GOBIN-${{ hashFiles('**/go.sum') }}-${{ hashFiles('aws/**') }}
        restore-keys: |
          ${{ runner.os }}-GOBIN-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-GOBIN-
    - uses: actions/cache@v1
      with:
        path: ${{ env.GOCACHE }}
        key: ${{ runner.os }}-GOCACHE-${{ hashFiles('aws/**') }}
        restore-keys: |
          ${{ runner.os }}-GOCACHE-
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-pkg-mod-
    - name: go build
      run: go build -i -o terraform-provider-aws_v99.99.99_x4 .
  terraform_providers_schema:
    name: terraform providers schema
    needs: [go_build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: bin
        key: ${{ runner.os }}-GOBIN-${{ hashFiles('**/go.sum') }}-${{ hashFiles('aws/**') }}
        restore-keys: |
          ${{ runner.os }}-GOBIN-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-GOBIN-
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false
    - name: terraform init
      run: |
        # We need a file to initialize the provider
        echo 'data "aws_partition" "example" {}' > example.tf
        terraform init -plugin-dir bin
    - run: terraform providers schema -json > schema.json
  tfproviderdocs:
    needs: [terraform_providers_schema]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ${{ env.GOBIN }}
        key: ${{ runner.os }}-GOBIN-${{ hashFiles('**/go.sum') }}-${{ hashFiles('aws/**') }}
        restore-keys: |
          ${{ runner.os }}-GOBIN-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-GOBIN-
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-pkg-mod-
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - run: go install github.com/bflad/tfproviderdocs
    - name: tfproviderdocs check
      run: |
        tfproviderdocs check \
          -allowed-resource-subcategories-file website/allowed-subcategories.txt \
          -ignore-side-navigation-data-sources aws_alb,aws_alb_listener,aws_alb_target_group,aws_kms_secret \
          -provider-name aws \
          -providers-schema-json schema.json \
          -require-resource-subcategory
